In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as lin

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

np.set_printoptions(precision=3, linewidth=150, suppress=True)


In [4]:
tab = np.array([[5, 4, 2, 5, 4, 2, 3, 1, 0, 2, 1, 4, 3, 1, 2],
       [5, 3, 1, 3, 4, 0, 3, 2, 1, 0, 2, 2, 2, 0, 1],
       [4, 3, 2, 5, 3, 1, 4, 1, 0, 1, 1, 4, 3, 0, 1],
       [0, 2, 3, 3, 2, 3, 2, 4, 3, 3, 1, 2, 3, 3, 2],
       [1, 2, 2, 4, 3, 1, 4, 3, 1, 1, 0, 1, 2, 2, 3],
       [1, 1, 2, 3, 2, 1, 4, 3, 0, 0, 1, 2, 3, 2, 2]])


In [5]:
cov = np.cov(tab)

val, vec = lin.eig(cov)
val = val.astype('float')  # on convertit puisqu'on sait que ce sont des réels
print("Valeurs propres de la matrice de covariance :", val,"\n")
print("Vecteurs propres de la matrice de covariance :\n", vec)

Valeurs propres de la matrice de covariance : [7.011 2.383 0.81  0.089 0.382 0.249] 

Vecteurs propres de la matrice de covariance :
 [[ 0.545  0.152 -0.487  0.561 -0.242  0.262]
 [ 0.487  0.219  0.66   0.128 -0.268 -0.436]
 [ 0.587 -0.021 -0.346 -0.621  0.3   -0.243]
 [-0.171 -0.456 -0.356  0.167 -0.333 -0.705]
 [ 0.212 -0.626  0.186 -0.295 -0.508  0.429]
 [ 0.214 -0.574  0.216  0.41   0.641  0.005]]


/var/folders/2c/_2pxcgcx3dg1z0y7lxk7nf080000gn/T/ipykernel_44697/78524939.py:4: ComplexWarning: Casting complex values to real discards the imaginary part
  val = val.astype('float')  # on convertit puisqu'on sait que ce sont des réels


In [17]:
(1/2.383)*cov @ vec[:,1]



array([ 0.152,  0.219, -0.021, -0.456, -0.626, -0.574])

In [8]:
print(vec[:,0])

[ 0.545  0.487  0.587 -0.171  0.212  0.214]


In [10]:
vec[:,0]@tab[:,0]

7.939531117269928

In [12]:
for i in range(14):
    print(vec[:,0]@tab[:,i])
    

7.939531117269928
5.702531201902928
3.092655449215036
8.10412212348372
6.616103636613148
1.5917174575357684
6.810766422491071
2.7026273370387073
0.18709259889881916
1.3778104878225261
2.150597080164158
5.804138263588241
4.9267077475970105
0.885144563577256


In [13]:
for i in range(14):
    print(vec[:,1]@tab[:,i])

0.5743808546660782
-1.5329700337797183
-3.284625984833884
-4.277065165298903
-2.51293451985396
-2.283511975059551
-4.678301140237845
-4.85199381135274
-1.7746847157246193
-1.7100119255721655
-0.4599704384445653
-1.7211551703803396
-3.5076595585775525
-3.61394293687751
